name: release-build-wheels

on:
  push:
    tags:
      - 'v*'

jobs:
  build-wheels:
    runs-on:  [self-hosted, p-dev-ws2040-03]
    
    strategy:
      fail-fast: false
      matrix:
        platform: ['manylinux2_28_x86_64']
        cuda-version: ['12.4']
        # cuda-version: ['12.4', '12.6', '12.8', '13.0']
        include:
          - cuda-version: "12.4"
            cuda-image: "pytorch/manylinux2_28-builder:cuda12.4"
          # - cuda-version: "12.6"
          #   cuda-image: "pytorch/manylinux2_28-builder:cuda12.6"
          # - cuda-version: "12.8"
          #   cuda-image: "pytorch/manylinux2_28-builder:cuda12.8"
          # - cuda-version: "13.0"
          #   cuda-image: "pytorch/manylinux2_28-builder:cuda13.0"
      
    env:
      CUDA_IMAGE: ${{ matrix.cuda-image }}
      PY_LIST: "/opt/python/cp38-cp38/bin/python /opt/python/cp39-cp39/bin/python /opt/python/cp310-cp310/bin/python /opt/python/cp311-cp311/bin/python /opt/python/cp312-cp312/bin/python /opt/python/cp313-cp313/bin/python"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure CUDA image exists
        run: |
          if ! docker image inspect $CUDA_IMAGE > /dev/null 2>&1; then
            echo "CUDA image not found. Pulling $CUDA_IMAGE..."
            docker pull $CUDA_IMAGE
          else
            echo "CUDA image $CUDA_IMAGE already exists locally."
          fi

      - name: Start manylinux CUDA builder container
        run: |
          mkdir -p ${{ runner.temp }}/build_temp
          container=$(docker run -td \
            --name "flaggems_builder_${{ matrix.cuda-version }}" \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ runner.temp }}/build_temp:/workspace/build \
            -v ${{ runner.temp }}/wheelhouse:/wheelhouse \
            -w /workspace \
            $CUDA_IMAGE)
          echo "CONTAINER=$container" >> $GITHUB_ENV

      - name: Install build dependencies inside container
        run: |
          docker exec -t $CONTAINER bash -c "
            set -e
            for PY in $PY_LIST; do
              echo \"Installing deps for \$PY\"
              \"\$PY\" -m pip install --upgrade pip setuptools wheel scikit_build_core \"cmake>=3.26\" -i https://pypi.tuna.tsinghua.edu.cn/simple
            done
          "
          
      - name: Build wheels for Python versions
        run: |
          docker exec -t $CONTAINER bash -c "
            set -e
            for PY in $PY_LIST; do
              echo '=========== Building wheel with' \$PY '==========='
              \"\$PY\" -m pip wheel . -w /wheelhouse --no-build-isolation --no-deps
            done
          "

      - name: Cleanup container
        if: always()
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q "flaggems_builder_${{ matrix.cuda-version }}"; then
            docker rm -f "flaggems_builder_${{ matrix.cuda-version }}"
            echo "Removed container flaggems_builder_${{ matrix.cuda-version }}"
          else
            echo "Container already removed."
          fi


      # - name: Fix wheel (auditwheel repair)
      #   run: |
      #     docker exec -t $CONTAINER bash -c "\
      #       auditwheel repair /wheelhouse/*.whl -w /wheelhouse/fixed \
      #     "

      # - name: Upload wheels to private PyPI
      #   run: |
      #     $PY_EXEC -m pip install --upgrade twine
      #     $PY_EXEC -m twine upload \
      #       --repository-url http://10.1.1.16/repository/pipy-private/ \
      #       -u testuser -p 'testuser@12345' \
      #       /wheelhouse/*.whl

      # - name: Upload wheels
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: wheel-${{ matrix.python-version }}-cuda${{ matrix.cuda-version }}
      #     path: ${{ runner.temp }}/wheelhouse/fixed/*.whl
      #     if-no-files-found: error
